### ISSUE TITLE
Which version of the textbook did you refer to?

### ISSUE THREAD

**Issue by JinraeKim** [Juju-botu/optimal-control-exercises#1]
Hi,

I'd like to know which version of the textbook you referred to.

I'm reading [1] and I found that Exercise 5.4 in this repo is different from what I have (maybe?) cuz the solution seems not match the Exercise.

- What I have
![image](https://user-images.githubusercontent.com/43136096/135224982-b519f441-9da0-4140-84ab-9576bbe9626d.png)

# Refs.
[1] D. Liberzon, Calculus of Variations and Optimal Control Theory: A Concise Introduction. Princeton ; Oxford: Princeton University Press, 2012.

**Comment by fedebotu** [comment]
Hello @JinraeKim ,

The book is made with homework from professor Donghwan Lee at KAIST. Unfortunately, I did not do the exercise numbering myself, so I left it as per the final submission.

Many exercises are taken from Liberzon's book (same 2012 version as you mentioned), but not all of them (and many are not in order indeed). I could not find a solution manual at the time, but searching in Google with certain keywords helped for most of the exercises!

Good luck with optimal control :)

(if you find mistakes, feedback, or have extra exercises to share, feel free to contribute ^^)

**Comment by JinraeKim** [comment]
@Juju-botu
Thank you for your reply and suggestion :)

**Comment by fedebotu** [comment]
I will add this in the README, closing for now!
